spring.application.name=BAN

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
# Logging SQL (optionnel)
logging.level.org.springframework.batch=INFO


# DataSource SQLite
spring.datasource.url=jdbc:sqlite:ban.db
spring.datasource.driver-class-name=org.sqlite.JDBC



# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always


spring.batch.job.enabled=false

# Initialise automatiquement le schéma de métadonnées Spring Batch
spring.batch.jdbc.initialize-schema=always


server.port=8081